print('PROGRAMA LOCALIZAÇÃO')
frase = input('Digite uma frase ').strip().upper()
print(f'Analisando {frase}...')
print('A letra A apareceu', frase.count('A'), 'vezes')
print('É vista pela primeira vez na posição',frase.find('A')+1)
qnt = len(frase)
frase = frase.split()
frase.reverse()
frase = ' '.join(frase)
ultima = (qnt - frase.find('A'))
print(f'É vista pela ultima vez na posição {ultima}')
