print('PROGRAMA DISSECAÇÃO')
valor = input ("Escolha um valor para ser dissecado ")
print (f'O Valor {valor} é do tipo', type(valor))
print ("É do tipo alnum ?", valor.isalnum())
print ('É do tipo numeric ?', valor.isnumeric())
print ('É do tipo decimal?',valor.isdecimal())
print ('É do tipo alpha?',valor.isalpha())
print ('É do tipo space?',valor.isspace())
print ('É do tipo upper?',valor.isupper())
print ('E do tipo lower?',valor.islower())
print ('É do tipo title?', valor.istitle())
